# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret quiz0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-dev.
# Re-seal:  kubeseal --cert sealed-secrets-dev.pem --format yaml \
#             --namespace sdk-apps-dev --name quiz0-secrets < raw-secret.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quiz0-secrets
  namespace: sdk-apps-dev
spec:
  encryptedData:
    API_KEY: AgA5aleacNS807TkYXlHEVwPhdVDB3gsuyfudV0RxaiLh311LS+OFeBZ3PMqzJ+ineO+xw2RAL/OSmSCMUhzXvL7cbyoUHTv0uGfRrrfdq0J+TA1qu54yTdS1aND6ZTplxV73NQ4PfBit/gIgJwEHs4QWDVwn1hcJDh3jtlalJocPuMb3qwYJTE33xOv60IRKNln+F8eYKZb5bJQ4r+ymc+ch2rwN/E8SRvhbHARqCU5ABpl1Ogm1tcXQs0uauFmzh9/BLv/9qJjDka0Ottf/FhpsLDzI3HmNUobBo3JU3N2XFfH119sPcnvb6Y26mDnSpnYqzBGMP0hfdtGtDvJ2dGQsCwKaBSXpKwvXsRvGjZDo13HAxEX8lR/H7OtiWFBf+79FNj8wkl9o7QozgIPGGhILmhLF6sFQilMdD2G0Z3fWaN3djOOpdJrgNMWLGewQ4oWt2rRo01Sf/QEB+RPUBpsyAfNp9HLzbE2ZkQqi/r7rTN8Vi6mV80dXyT/hAgaE8G7GkSATZIRckggwOYdlO5Vh7QmRs4do+hkSspa7HXG/M3icjk/aXwU043jEc5j/YdvisUsGmD3OB/l6jBiHzxdgDAAdJ//0kbOkV9TwPgCwYW8TqbH6F1pfKGs1XKbcj1cXuREftvlBmsQRbRiIj3IagMLIfZmxvbbpPfi6wG4NftiAOEcrbF/JQR+MyQesWNEYyztwXMaRaJqiuyZjtuUEK5WVMKaIv6D0Ih7QZwFIy81VSCHHqFukLQeFlqV30U=
    INTERACTIVE_SECRET: AgBHpBa2MGyW3qCfKzZpFW70IZKuzzdBG4mj7Xq+wZv1trVr3MSKH2qmPNwxdka1xxBQUxKT7wq1ULeRYbEee1TCxPE0q4bkfLlxrGEh8YpXWCN/BAqB1maiFCjFjvqHENvDnhow+PPDmIQQ8PvontMY+KAzsyt3lCsYBAK5D0jOEaaRXaxFq6rYaNkdEzEIG1arnS0eYh5XlLmBKg9wifdI6u8wSst/8rtdJFsXGBr+TjpB/dxmBPG7s4p9jaFJayTsUUg+YcX41HR8eBvxAiJ2c/4P1j0xfxCR4i/4QaIjmFACRCoD51b45PRTYdNmhSrhu/+4DVuwc+kIL7Dw+vot3xhximpzGzEHrf2Gfy+RlViovxv05Ti/2d9gpJtMGA1XYdcTVCUvmrJrj3G8hflyI1Qr8bSy3th62uBNPFCz/pLhPUbpv2ffCrnpj4XLNV1nUc9R09oP0sO6mlqx69/GIrOqDYvM5+t+MxMJQPbhGczu69NBM9rkHJr27V1lUbLK0pGXqs6FXuTy68UI1Av0NtZnGseBDerevZzSZmSUTV0YGb3z0oH4wqT3k+SyIJ8g24EGwY0xA1VFBOM439Si8QeaRnZt8Duv6BuUboxZL+K6wHp0AEu+1oFxmFxNG09ZoXopSe1ioIV2G7Qm6zhF3KgVbDof1x25wYTOiCbdW8xjA+gl3fxytZ0XT1V9oLSZ+96lOeSckx89/0pLSZPZxQYDFVYX4zSTm90YB7h/cG4XCZM7WTRwhpGUNnZdZV8=
  template:
    metadata:
      name: quiz0-secrets
      namespace: sdk-apps-dev
    type: Opaque
