export { getVisitor } from "./getVisitor.js";
export { getDroppedAssets } from "./getDroppedAsset.js";
export { updateTimestamp } from "./updateTimestamp.js";
export { getTimestamp } from "./getTimestamp.js";
// export { registerUserAnswer } from "./registerUserAnswer.js";
export { clear } from "./clear.js";
export { resetTimer } from "./resetTimer.js";
export { resetGame } from "./resetGame.js";
// export { leaderboard } from "./leaderboard.js";
export { getQuestionsStatistics } from "./getQuestionsStatistics.js";
export { getAllQuestionAssets } from "./getAllQuestionAssets.js";
export { updateQuestion } from "./updateQuestion.js";
export { reloadIframe } from "./reloadIframe.js";
